### ISSUE TITLE
Is there any python demo?

### ISSUE THREAD

**Issue by 20XYSong** [PinataFarms/FEARTracker#1]
Hallo, thanks for you awesome work. I found the FEARDemo here only provide swift version on iOS. Will you further provide a version of python? Or could you please give me some instruction to write an python demo? Thanks a lot!

**Comment by KupynOrest** [comment]
@20XYSong thanks for mentioning, we've just added it today

https://github.com/PinataFarms/FEARTracker/pull/2

**Comment by 20XYSong** [comment]
Thanks for your help！o(￣▽￣)ｄ
