### ISSUE TITLE
Is there a code for FEAR-M and FEAR-XL ?

### ISSUE THREAD

**Issue by kangben258** [PinataFarms/FEARTracker#10]

**Comment by borsukvasyl** [comment]
Hi
We plan to release it soon. If you need to get it sooner, you can manually add FEAR-M (ResNet) and FEAR-XL (RegNet) encoder [here](https://github.com/PinataFarms/FEARTracker/blob/main/model_training/model/blocks.py#L8)

**Comment by NewboySoCool** [comment]
> Hi We plan to release it soon. If you need to get it sooner, you can manually add FEAR-M (ResNet) and FEAR-XL (RegNet) encoder [here](https://github.com/PinataFarms/FEARTracker/blob/main/model_training/model/blocks.py#L8)

I'll have a try !

**Comment by NewboySoCool** [comment]
which  the version of  RegNet? X or Y
