### ISSUE TITLE
could you update the raw results,thank you.

### ISSUE THREAD

**Issue by kangben258** [PinataFarms/FEARTracker#12]
could you update the raw results,thank you.

**Comment by borsukvasyl** [comment]
Hi
What do you mean by raw results?

**Comment by kangben258** [comment]
The txt file tested on the dataset

**Comment by borsukvasyl** [comment]
Which datasets? Or do you mean benchmarks from the result tables?

**Comment by kangben258** [comment]
yeah, the .txt file of these benchmark, such as LaSOT.

**Comment by romanvey** [comment]
Hi,
Here are the raw results for our models:
https://drive.google.com/drive/folders/1fdXgVV_6L5iQ5xcQAudYyU5WZVfsoyUm?usp=share_link
For evaluation, we use the Got10K toolkit: https://github.com/got-10k/toolkit

**Comment by kangben258** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        Thank you very much!!!
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1969868860
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 11/15/2022 ***@***.***> wrote： 



Hi,
Here are the raw results for our models:
https://drive.google.com/drive/folders/1fdXgVV_6L5iQ5xcQAudYyU5WZVfsoyUm?usp=share_link
For evaluation, we use the Got10K toolkit: https://github.com/got-10k/toolkit

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
