### ISSUE TITLE
from mobile_cv.model_zoo.models.fbnet_v2 import fbnet ModuleNotFoundError: No module named 'mobile_cv'

### ISSUE THREAD

**Issue by fubai3** [PinataFarms/FEARTracker#22]
Hello When I run the demo_video file, the following error is displayed, the mobile_cv file is missing：
from mobile_cv.model_zoo.models.fbnet_v2 import fbnet
ModuleNotFoundError: No module named 'mobile_cv'

**Comment by t-martyniuk** [comment]
you need this: https://github.com/facebookresearch/mobile-vision

```
git clone https://github.com/facebookresearch/mobile-vision.git
cd mobile-vision
pip install -e .
```
