### ISSUE TITLE
Has the FEAR-M and FEAR-XL models been announced? 

### ISSUE THREAD

**Issue by Bigelephant0** [PinataFarms/FEARTracker#3]
Only FEAR-XS in checkpoints

**Comment by borsukvasyl** [comment]
Hi
We still need some time to sort out the complete training and inference code. We'll release FEAR-M and FEAR-XL model checkpoints when everything will be ready.

**Comment by Bigelephant0** [comment]
Thanks for your generous！

**Comment by NewboySoCool** [comment]
> Hi We still need some time to sort out the complete training and inference code. We'll release FEAR-M and FEAR-XL model checkpoints when everything will be ready.

which the version of resnet? resnet50 or 101?    and the version of regnet?  regnetX or Y?
