### ISSUE TITLE
How to convert to onnx or torchscript?

### ISSUE THREAD

**Issue by NewboySoCool** [PinataFarms/FEARTracker#30]
Hello, I encounter a question when I convert FEAR-XS.ckpt to onnx or pt(torchscript).
I want to use the `torch.jit.script（）` to convert FEAR-XS-NoEmbs.ckpt to  onnx or pt(torchscript)  to complete a deploying  task on the NPU device. 
The Neck and Connector of model is ok, but the encoder can not be converted to torchscript.

I use the scirpt following:
```
from model_training.utils.hydra import load_hydra_config_from_path
from hydra.utils import instantiate
from model_training.utils.torch import load_from_lighting

config_path= "model_training/config",
config_name= "fear_tracker",
weights_path = 'FEAR-XS-NoEmbs.ckpt'
model = instantiate(config["model"])
model = load_from_lighting(model, weights_path).to('cpu').eval()

template_input = torch.randn(1, 3, 128, 128)
search_input = torch.randn(1, 3, 256, 256)
traced_script_module = torch.jit.script(model )
traced_script_module.save('./FEAR-XS-NoEmbs-torchscript.pt')
print('cpkt2pt done')
```

```
RuntimeError:
FBNetBackbone has no attribute 'arch_def' (This attribute exists on python module, but we failed to convert Python type "dict" to a Torchscript type).
File "mobile-vision/mobile_cv/model_zoo/fbnet_v2.py"
     @property
    def arch_def(self):
        return self.backbone.arch_def
```
What can I do for conver FEAR-XS-NoEmbs.ckpt to onnx or pt(torch script)?

**Comment by NewboySoCool** [comment]
It'done

**Comment by Zalways** [comment]
> It'done

hello！ i'm going to convert this model to onnx or torchscript too, you said you have done, i want to know is this converted onnx or torchscript can work well in cpu (speed and track accurance), and also i want to use this model in c++ environment, any advice?

**Comment by FreshmanMa** [comment]
> > It'done
> 
> hello！ i'm going to convert this model to onnx or torchscript too, you said you have done, i want to know is this converted onnx or torchscript can work well in cpu (speed and track accurance), and also i want to use this model in c++ environment, any advice?

to onnx, u can have a try the code following:

**Comment by NewboySoCool** [comment]
> > It'done
> 
> hello！ i'm going to convert this model to onnx or torchscript too, you said you have done, i want to know is this converted onnx or torchscript can work well in cpu (speed and track accurance), and also i want to use this model in c++ environment, any advice?

You can try it by `torch.onnx.export()`

**Comment by Zalways** [comment]
> > > It'done
> > 
> > 
> > hello！ i'm going to convert this model to onnx or torchscript too, you said you have done, i want to know is this converted onnx or torchscript can work well in cpu (speed and track accurance), and also i want to use this model in c++ environment, any advice?
> 
> You can try it by `torch.onnx.export()`

thanks！i'v converted sucsessfully! but there is still some problems when i use the onnx model to track. so i'll be grateful if you could provide your onnx or torchscript inference  demo scripts!

**Comment by NewboySoCool** [comment]
> > > > It'done
> > > 
> > > 
> > > hello！ i'm going to convert this model to onnx or torchscript too, you said you have done, i want to know is this converted onnx or torchscript can work well in cpu (speed and track accurance), and also i want to use this model in c++ environment, any advice?
> > 
> > 
> > You can try it by `torch.onnx.export()`
> 
> thanks！i'v converted sucsessfully! but there is still some problems when i use the onnx model to track. so i'll be grateful if you could provide your onnx or torchscript inference demo scripts!

sorry， I did not do the inference by onnx! For me, Onnx is just the intermediate model which is converted in to .rknn model.

**Comment by ST5712** [comment]
> thanks！i'v converted sucsessfully! but there is still some problems when i use the onnx model to track. so i'll be grateful if you could provide your onnx or torchscript inference demo scripts!

Hi @zalways,

I noticed your earlier comment about working with the ONNX model in this issue. I wanted to ask if you happened to write an inference script for using the ONNX model. If so:

- How were the results and performance, particularly the speed of inference?
- Would it be possible for you to share the script or provide some insights into how you implemented it?

I’m exploring a similar setup and would greatly appreciate your guidance. Thank you in advance!
