### ISSUE TITLE
About dual-template representation and dynamic template update.

### ISSUE THREAD

**Issue by MisakaMikt** [PinataFarms/FEARTracker#6]
Will you open source the code for this part? I think that's a very important part of your work!

**Comment by borsukvasyl** [comment]
Hey
Sorry for the late response. We plan to release it in the near future with pre-trained weights of FEAR models with a dynamic template update. We are working on separating its training and inference code from our codebase into this repository.

**Comment by adityab** [comment]
Also very interested in this. Looking forward!

**Comment by assertdebug** [comment]
@borsukvasyl    When can you release the code?
