### ISSUE TITLE
The ios version

### ISSUE THREAD

**Issue by songtianhui** [PinataFarms/FEARTracker#7]
Can you provide the version of macos，xcode，ios in your experiments？
I am not familiar with
iOS development and encountered many errors when building the project😢
Thank you！

**Comment by borsukvasyl** [comment]
Hey
Sory for the late response. I'm building it on macOS 12.6, iOS 15.6.1, and Xcode 14.0.1. But it should build on any new versions. What errors did you get?

**Comment by songtianhui** [comment]
OK. It runs successfully!
Thanks!
