### ISSUE TITLE
How to convert model to ONNX format?(GPU)

### ISSUE THREAD

**Issue by arminbiglari** [PinataFarms/FEARTracker#9]
Hello, Thanks for your GREAT work.
i'm using your project to track any object on jetson nano with 16 FPS. since 16 FPS is disappointing, i have to increase the FPS, i think if  i convert the model to ONNX format with FP16 conversion, model will run faster. so my question is how to convert .ckpt model to .onnx(GPU)?

**Comment by borsukvasyl** [comment]
Hi
ONNX is not a part of this work. You can easily convert model to ONNX format by following the steps described in [official PyTorch documentation](https://pytorch.org/docs/stable/onnx.html).

**Comment by arminbiglari** [comment]
Hello again, Thanks for your replay.
i have received a Jetson Xavier NX with 8 GB RAM and 21 TOP(~= 6 TFlops),also for more information  my Jetson nano has 4 GB RAM with 472 GFlops. 
inference speed on Jetson nano in about 17 FPS and  inference speed on Xavier NX is also 17 FPS!.
why there is no difference in their FPS?! is it the limitation of your model? 
i also tested your model on local computer with RTX3070 graphic card and watch the GPU utilization, it was never higher than 10%.

local computer: torch version 1.11.0, CUDA version 11.5, python version 3.8.10
Jetson Nano: torch version 1.8.1, CUDA version 10.2, python version 3.6.9
Jetson Xavier NX: torch version 1.8.0, CUDA version 10.2, python version 3.6.9

**Comment by borsukvasyl** [comment]
Hi
Make sure you run it on GPU and try running the model in torch jit format with optimizations (https://pytorch.org/docs/stable/generated/torch.jit.optimize_for_inference.html). Also, try converting the model to ONNX (https://pytorch.org/docs/stable/onnx.html) or TensorRT (https://pytorch.org/TensorRT/) to speed it up even more than PyTorch does.

**Comment by arminbiglari** [comment]
i did not change your code, is your model running on GPU?
also if i optimize and quantize the model with jit, i can not convert it to ONNX. 
if only i optimize your model to jit, can i use it? or i should optimize backbone, neck and connector separately then use them together?

**Comment by borsukvasyl** [comment]
> i did not change your code, is your model running on GPU?

What file exactly did you use? Make sure CUDA is available, and you move the model to CUDA before the inference.

> also if i optimize and quantize the model with jit, i can not convert it to ONNX

Follow the official PyTorch to ONNX documentation. You don't need to optimize the jit model when converting it to ONNX. Just convert it to jit and then to ONNX. Output ONNX model can be further optimized using ONNX optimization tools.

> if only i optimize your model to jit, can i use it? or i should optimize backbone, neck and connector separately then use them together?

Yes, you can convert the whole model and use it

**Comment by arminbiglari** [comment]
Thank you, i will check them out.

**Comment by NewboySoCool** [comment]
> Thank you, i will check them out.

Hello， have you converted it to ONNX? There is something wrong when i do it.

**Comment by Zalways** [comment]
> Hello, Thanks for your GREAT work. i'm using your project to track any object on jetson nano with 16 FPS. since 16 FPS is disappointing, i have to increase the FPS, i think if i convert the model to ONNX format with FP16 conversion, model will run faster. so my question is how to convert .ckpt model to .onnx(GPU)?

hi , i also want to conver the model to onnx or torchscript so that i can use it in cpu&c++ environment, can you share your convert script ? and i want to know the speed on cpu will satisfy the real-time require? any advice is welcome!
